/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotek;

import static apotek.Apotek.res;
import static apotek.Apotek.stm;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yodha
 */
public final class Bendahara extends javax.swing.JFrame implements SQL{
    private Apotek apt;
    private DefaultTableModel tb;

    /**
     * Creates new form Penghasilan
     */
    public Bendahara() {
        connectsql();
        initComponents();
        tableDisplay();
    }
    
    @Override
    public void connectsql() {
        apt = new Apotek();
    }

    @Override
    public void tableDisplay() {
        tb = new DefaultTableModel();
        tb.addColumn("ID");
        tb.addColumn("Harga");
        jTable_bendahara.setModel(tb);
    }
    
    private void tableobat(){
        try {          
            tb = new DefaultTableModel();
            tb.addColumn("ID");
            tb.addColumn("Harga");     
            jTable_bendahara.setModel(tb);
            int total = 0;
            res = stm.executeQuery("select ID,total_harga from customer");
            while (res.next()) {
                tb.addRow(new Object[]{
                    res.getString("ID"),
                    res.getString("Total_Harga"),
                });
                total+=res.getInt("Total_Harga");
            }
            text_tabel.setText("Total Penjualan Obat");
            jTextField_obat.setText(Integer.toString(total));
        } catch (SQLException ex) {
            Logger.getLogger(Bendahara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void pegawai(){
        try {          
            tb = new DefaultTableModel();
            tb.addColumn("ID");
            tb.addColumn("Gaji");
            jTable_bendahara.setModel(tb);
            int total = 0;
            res = stm.executeQuery("select ID,Gaji from karyawan");
            while (res.next()) {
                tb.addRow(new Object[]{
                    res.getString("ID"),
                    res.getString("Gaji"),
                });
                total+=res.getInt("Gaji");
            }
            text_tabel.setText("Total Gaji Pegawai");
            jTextField_Pegawai.setText(Integer.toString(total));
        } catch (SQLException ex) {
            Logger.getLogger(Bendahara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void stock(){
        try {          
            tb = new DefaultTableModel();
            tb.addColumn("ID");
            tb.addColumn("stock");
            tb.addColumn("Harga");
            jTable_bendahara.setModel(tb);
            int total = 0;
            res = stm.executeQuery("select ID,stock,Harga from stockobat");
            while (res.next()) {
                tb.addRow(new Object[]{
                    res.getString("ID"),
                    res.getString("stock"),
                    res.getString("Harga"),
                });
                total+=res.getInt("Harga")*res.getInt("stock");
            }
            text_tabel.setText("Total Harga Stock Obat");
            jTextField_stock.setText(Integer.toString(total));
        } catch (SQLException ex) {
            Logger.getLogger(Bendahara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_bendahara = new javax.swing.JTable();
        btn_obat = new javax.swing.JButton();
        btn_gaji = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_obat = new javax.swing.JTextField();
        jTextField_Pegawai = new javax.swing.JTextField();
        jTextField_stock = new javax.swing.JTextField();
        text_tabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.lightGray);

        jPanel3.setBackground(java.awt.Color.gray);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obat.png"))); // NOI18N

        jButton_back.setBackground(new java.awt.Color(255, 51, 51));
        jButton_back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_back.setText("BACK");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_back)
                .addGap(31, 31, 31))
        );

        jTable_bendahara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_bendahara);

        btn_obat.setBackground(new java.awt.Color(255, 255, 255));
        btn_obat.setForeground(new java.awt.Color(0, 0, 0));
        btn_obat.setText("Total Penjualan Obat");
        btn_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obatActionPerformed(evt);
            }
        });

        btn_gaji.setBackground(new java.awt.Color(255, 255, 255));
        btn_gaji.setForeground(new java.awt.Color(0, 0, 0));
        btn_gaji.setText("Total Gaji Pegawai");
        btn_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gajiActionPerformed(evt);
            }
        });

        btn_stock.setBackground(new java.awt.Color(255, 255, 255));
        btn_stock.setForeground(new java.awt.Color(0, 0, 0));
        btn_stock.setText("Total Harga Stock Obat");
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bendahara Apotek");

        jTextField_obat.setEditable(false);
        jTextField_obat.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_obat.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_Pegawai.setEditable(false);
        jTextField_Pegawai.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Pegawai.setForeground(new java.awt.Color(0, 0, 0));

        jTextField_stock.setEditable(false);
        jTextField_stock.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_stock.setForeground(new java.awt.Color(0, 0, 0));

        text_tabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_tabel.setForeground(new java.awt.Color(0, 0, 0));
        text_tabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_tabel.setText("Nama Tabel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_stock)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_tabel)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_obat)
                    .addComponent(jTextField_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gaji)
                    .addComponent(jTextField_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_stock)
                    .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void btn_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obatActionPerformed
        // TODO add your handling code here:
        tableobat();
        jTextField_Pegawai.setText("");
        jTextField_stock.setText("");
    }//GEN-LAST:event_btn_obatActionPerformed

    private void btn_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gajiActionPerformed
        // TODO add your handling code here:
        pegawai();
        jTextField_obat.setText("");
        jTextField_stock.setText("");
    }//GEN-LAST:event_btn_gajiActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        // TODO add your handling code here:
        stock();
        jTextField_Pegawai.setText("");
        jTextField_obat.setText("");
    }//GEN-LAST:event_btn_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bendahara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bendahara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gaji;
    private javax.swing.JButton btn_obat;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton jButton_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_bendahara;
    private javax.swing.JTextField jTextField_Pegawai;
    private javax.swing.JTextField jTextField_obat;
    private javax.swing.JTextField jTextField_stock;
    private javax.swing.JLabel text_tabel;
    // End of variables declaration//GEN-END:variables

    
}
